#!/usr/bin/python

import urllib3
import base64
import string
import sys
import os

def getInfo(ports):
	host = os.environ["host"]
	username = os.environ["username"]
	password = os.environ["password"]

	url='/html/status/ethinfo.asp'

	http = urllib3.HTTPConnectionPool(host)
	
	# Login
	r1 = http.request('GET','/asp/GetRandCount.asp')
	
	## Parameters
	fields = {'': 'x.X_HW_Token={}'.format(r1.data.decode('utf-8-sig'))}
	
	## Headers
	password64 = base64.b64encode(str.encode(password)).decode('ascii')
	cookie = 'Cookie=UserName:{}:PassWord:{}:Language:english:id=-1'.format(username, password64)
	header = {'Referer': 'http://{}/'.format(host), 'Cookie' : cookie}
	
	r = http.request('POST', '/login.cgi', headers=header, fields=fields)
	header2 = {'Cookie': r.headers['set-cookie']}

	# Random page
	http.request('GET', '/frame.asp', headers=header2)

	# Data
	r2 = http.request('GET', url, headers=header2)	
	data = r2.data.decode('UTF-8').split('\r\n')

	eths = []
	for d in data:
		if "var userEthInfos" in d:
			d = d.replace("var userEthInfos = new Array(","").replace(",null);","").replace(")","").replace("\"","")
			eths = d.split("new LANStats(")
	
	dig = 0
	for eth in eths:
		if(eth):
			tmp = eth.split(",")
			print("{}up.value {}".format(ports[dig]['name'], tmp[2]))
			print("{}down.value {}".format(ports[dig]['name'], tmp[4]))
			dig = dig + 1

def printInfo(ports):
	p = """graph huawei
graph_title huawei traffic
graph_args --base 1000 --upper-limit 250000000 --lower-limit -250000000 --rigid
graph_vlabel bits in (-) / out (+)
graph_category network
graph_order """

	for port in ports:
		p += "{0}down {0}up ".format(port['name'])

	for port in ports:
		p += """
{0}down.label received
{0}down.type DERIVE
{0}down.graph no
{0}down.cdef {0}down,8,*
{0}up.label {0}
{0}up.type DERIVE
{0}up.negative {0}down
{0}up.cdef {0}up,8,*
{0}up.colour {2}
{0}up.draw {1}""".format(port['name'], "AREA" if port['name'] == ports[0]['name'] else "STACK", port['colour'])

	print(p)

# Ports

ports = [
	{"name": "LAN1", "colour": "00CC00"},
	{"name": "LAN2", "colour": "0022FF"},
	{"name": "LAN3", "colour": "FF0000"},
	{"name": "LAN4", "colour": "FFCC00"}
]

# Main

if len(sys.argv) > 1 and sys.argv[1] == 'config':
	printInfo(ports)
else:
	getInfo(ports)

